### ISSUE TITLE
Ściągnąć wszystkie htmle do pzbs

### ISSUE THREAD

**Issue by michzimny** [PZBS/liga-playoff#2]
> Do tego w 85afaca musiałem ręcznie ustawić teamy i wynik tych dwóch meczów, które były grane przed zjazdem, bo nie dość, że długie nazwy się nie zgadzały, to jeszcze wyniki wiszą na serwerze, który podaje jakieś dziwne nagłówki HTTP i kodowanie polskich znaków się rozwalało w pobranych nazwach.

Planuję ściągnąć wszystkie wyniki opublikowane na innych serwerach do pzbs.

**Comment by emkael** [comment]
W przypadku tamtych meczów to chyba i tak nie pomoże, bo pełne nazwy teamów się różnią.
Ale sam pomysł jak najbardziej słuszny.
